name: dailybite
description: AI-powered food photo calorie tracker mobile app
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.10.0"

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.4.9

  # HTTP Client
  dio: ^5.3.2

  # Secure Storage
  flutter_secure_storage: ^9.0.0

  # Image handling
  image_picker: ^1.0.4
  camera: ^0.10.5+5

  # UI Components
  material_symbols_icons: ^4.2719.3
  cached_network_image: ^3.3.0

  # Local Notifications
  flutter_local_notifications: ^16.3.0

  # Permissions
  permission_handler: ^11.0.1

  # Utilities
  intl: ^0.18.1
  shared_preferences: ^2.2.2

  # Navigation
  go_router: ^12.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true
